# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
      - main
      - develop
      - release/*
    exclude:
      - azure*-pipelines.yml
  paths:
    include:
      - src/**
      - tests/**
    exclude:
      - azure**

pool:
  vmImage: ubuntu-latest

stages:
- stage: Build
  displayName: Build and push image
  jobs:
  - job: Build
    displayName: Build
    steps:
    - script: |
        echo "Building the Docker image..."
      displayName: 'Build Docker image'
    - script: |
        echo "Pushing the Docker image..."
      displayName: 'Push Docker image'
    - script: |
        echo "Running tests..."
      displayName: 'Run tests'
    - script: |
        echo "Restore dependencies..."
      displayName: 'Restore dependencies'

- stage: Test
  displayName: Unit Tests
  dependsOn: Build
  isSkippable: false
  jobs:
  - job: TestJob
    displayName: TestJob
    steps:
    - script: |
        echo "Running unit tests..."
      displayName: 'Run unit tests'
    
